import type { SettingsSchema } from "./settings-schema";

/**
 * `site_settings` 行的声明式 schema，复用与插件/主题相同的 schema 机制，
 * 使 /admin/settings 是单一通用表单。theme/page 相关下拉选项由设置页在
 * 运行时注入。
 */
export const SITE_SETTINGS_SCHEMA: SettingsSchema = [
  {
    key: "general",
    label: "常规",
    icon: "Settings",
    description: "站点身份信息，出现在标题栏、页头、页脚与分享卡片上。",
    fields: [
      { key: "siteTitle", label: "站点名称", type: "text", default: "OboePress", half: true },
      { key: "tagline", label: "副标题 / 标语", type: "text", default: "", half: true },
      {
        key: "siteDescription",
        label: "站点描述",
        type: "textarea",
        default: "",
        help: "用于首页 meta description 与 RSS 描述。",
      },
      { key: "logoUrl", label: "Logo", type: "image", default: "" },
      { key: "faviconUrl", label: "Favicon", type: "image", default: "" },
      { key: "footerText", label: "页脚文字", type: "text", default: "" },
      { key: "icpNumber", label: "备案号", type: "text", default: "", half: true },
      {
        key: "activeThemeSlug",
        label: "当前主题",
        type: "select",
        default: "default",
        half: true,
        options: [],
        help: "细节调整请到「主题」页面的设置面板。",
      },
      { key: "socialLinks", label: "社交链接", type: "links", default: [] },
    ],
  },
  {
    key: "reading",
    label: "阅读",
    icon: "BookOpen",
    description: "首页展示方式、分页数量与摘要长度 —— 对应 WordPress 的「阅读设置」。",
    fields: [
      {
        key: "homeDisplay",
        label: "首页显示",
        type: "select",
        default: "latest",
        options: [
          { value: "latest", label: "最新文章列表" },
          { value: "page", label: "指定的静态页面" },
        ],
      },
      {
        key: "homePageId",
        label: "作为首页的页面",
        type: "select",
        default: "",
        half: true,
        options: [],
        showIf: { key: "homeDisplay", equals: "page" },
      },
      {
        key: "postsPageId",
        label: "作为文章列表的页面",
        type: "select",
        default: "",
        half: true,
        options: [],
        showIf: { key: "homeDisplay", equals: "page" },
      },
      {
        key: "postsPerPage",
        label: "每页文章数",
        type: "number",
        default: 10,
        min: 1,
        max: 100,
        half: true,
      },
      {
        key: "excerptLength",
        label: "摘要字数",
        type: "number",
        default: 160,
        min: 40,
        max: 600,
        half: true,
        help: "文章未手写摘要时，自动截取的长度。",
      },
      { key: "feedItems", label: "RSS 条目数", type: "number", default: 20, min: 1, max: 100, half: true },
      {
        key: "feedContent",
        label: "RSS 输出内容",
        type: "select",
        default: "excerpt",
        half: true,
        options: [
          { value: "excerpt", label: "仅摘要" },
          { value: "full", label: "全文" },
        ],
      },
      { key: "group_locale", label: "本地化", type: "group" },
      {
        key: "language",
        label: "站点语言",
        type: "select",
        default: "zh-CN",
        half: true,
        options: [
          { value: "zh-CN", label: "简体中文" },
          { value: "zh-TW", label: "繁体中文" },
          { value: "en", label: "English" },
          { value: "ja", label: "日本語" },
        ],
      },
      {
        key: "timezone",
        label: "时区",
        type: "text",
        default: "Asia/Shanghai",
        half: true,
        placeholder: "Asia/Shanghai",
      },
      {
        key: "dateFormat",
        label: "日期格式",
        type: "select",
        default: "YYYY-MM-DD",
        options: [
          { value: "YYYY-MM-DD", label: "2026-08-24" },
          { value: "YYYY年M月D日", label: "2026年8月24日" },
          { value: "MMM D, YYYY", label: "Aug 24, 2026" },
          { value: "D/M/YYYY", label: "24/8/2026" },
        ],
      },
    ],
  },
  {
    key: "seo",
    label: "SEO",
    icon: "Search",
    description:
      "标题模板支持 %title% / %site% / %tagline% 占位符。这些值会写入每个页面的 <head>。",
    fields: [
      {
        key: "seoTitleTemplate",
        label: "标题模板",
        type: "text",
        default: "%title% - %site%",
        placeholder: "%title% - %site%",
      },
      {
        key: "seoDefaultDescription",
        label: "默认描述",
        type: "textarea",
        default: "",
        help: "文章/页面没有自己的描述时使用。",
      },
      {
        key: "seoKeywords",
        label: "默认关键词",
        type: "text",
        default: "",
        placeholder: "逗号分隔",
      },
      {
        key: "seoRobots",
        label: "robots 指令",
        type: "select",
        default: "index,follow",
        half: true,
        options: [
          { value: "index,follow", label: "index,follow（允许收录）" },
          { value: "index,nofollow", label: "index,nofollow" },
          { value: "noindex,follow", label: "noindex,follow" },
          { value: "noindex,nofollow", label: "noindex,nofollow（完全屏蔽）" },
        ],
      },
      {
        key: "twitterCard",
        label: "Twitter 卡片",
        type: "select",
        default: "summary_large_image",
        half: true,
        options: [
          { value: "summary_large_image", label: "大图" },
          { value: "summary", label: "摘要" },
        ],
      },
      { key: "twitterSite", label: "Twitter @账号", type: "text", default: "", half: true },
      { key: "ogImageUrl", label: "默认分享图", type: "image", default: "" },
    ],
  },
  {
    key: "comments",
    label: "评论",
    icon: "MessageSquare",
    description:
      "评论系统可在「系统自带」与第三方（Artalk / Giscus / Waline / Twikoo / Disqus / Utterances）之间切换；头像源决定内置评论里头像的解析方式（含 QQ 邮箱直出 QQ 头像）。",
    fields: [
      { key: "commentsEnabled", label: "开启评论", type: "switch", default: true, half: true },
      {
        key: "requireNameEmail",
        label: "游客必须填昵称与邮箱",
        type: "switch",
        default: false,
        half: true,
      },
      {
        key: "commentModeration",
        label: "所有评论先进审核队列",
        type: "switch",
        default: false,
      },
      {
        key: "commentModerationWords",
        label: "待审关键词",
        type: "textarea",
        default: "",
        placeholder: "广告\n赌博",
        help: "每行一个；命中的评论标记为待审核。",
      },
      { key: "group_provider", label: "评论系统", type: "group" },
      {
        key: "commentProvider",
        label: "评论来源",
        type: "select",
        default: "builtin",
        help: "选择「系统自带」使用本站数据库存储评论；其余为第三方评论服务。",
        options: [
          { value: "builtin", label: "系统自带（内置数据库）" },
          { value: "artalk", label: "Artalk（自建）" },
          { value: "giscus", label: "Giscus（GitHub 讨论）" },
          { value: "waline", label: "Waline（valine 继任）" },
          { value: "twikoo", label: "Twikoo（腾讯云/私有）" },
          { value: "disqus", label: "Disqus" },
          { value: "utterances", label: "Utterances（GitHub Issues）" },
          { value: "none", label: "不显示评论" },
        ],
      },
      {
        key: "artalkServer",
        label: "Artalk 服务端地址",
        type: "text",
        default: "",
        placeholder: "https://comments.example.com",
        showIf: { key: "commentProvider", equals: "artalk" },
        help: "填写你的 Artalk 后端地址（含 http(s)://）。",
      },
      {
        key: "artalkSite",
        label: "Artalk 站点名称",
        type: "text",
        default: "",
        placeholder: "我的博客",
        half: true,
        showIf: { key: "commentProvider", equals: "artalk" },
      },
      {
        key: "giscusRepo",
        label: "Giscus 仓库",
        type: "text",
        default: "",
        placeholder: "owner/repo",
        showIf: { key: "commentProvider", equals: "giscus" },
      },
      {
        key: "giscusRepoId",
        label: "仓库 ID",
        type: "text",
        default: "",
        placeholder: "MDEwOlJlcG9zaXRvcnkxMjk3NzE= ",
        showIf: { key: "commentProvider", equals: "giscus" },
        help: "在仓库「Discussions」设置页或 giscus.app 获取。",
      },
      {
        key: "giscusCategory",
        label: "分类",
        type: "text",
        default: "General",
        half: true,
        showIf: { key: "commentProvider", equals: "giscus" },
      },
      {
        key: "giscusCategoryId",
        label: "分类 ID",
        type: "text",
        default: "",
        half: true,
        placeholder: "DIC_kwDOExample",
        showIf: { key: "commentProvider", equals: "giscus" },
      },
      {
        key: "giscusMapping",
        label: "讨论映射",
        type: "select",
        default: "pathname",
        half: true,
        showIf: { key: "commentProvider", equals: "giscus" },
        options: [
          { value: "pathname", label: "路径名（推荐）" },
          { value: "url", label: "URL" },
          { value: "title", label: "标题" },
          { value: "og-desc", label: "Og 描述" },
          { value: "issue-number", label: "Issue 编号" },
          { value: "specific-term", label: "特定词条" },
        ],
      },
      {
        key: "giscusReactions",
        label: "启用 Reaction",
        type: "switch",
        default: true,
        half: true,
        showIf: { key: "commentProvider", equals: "giscus" },
      },
      {
        key: "giscusTheme",
        label: "主题（可选）",
        type: "text",
        default: "",
        placeholder: "preferred_color_scheme / dark / light",
        showIf: { key: "commentProvider", equals: "giscus" },
        help: "留空跟随系统；可填 dark / light 或 Giscus 主题名。",
      },
      {
        key: "walineServer",
        label: "Waline 服务端地址",
        type: "text",
        default: "",
        placeholder: "https://waline.example.com",
        showIf: { key: "commentProvider", equals: "waline" },
      },
      {
        key: "twikooEnvId",
        label: "Twikoo 环境 ID",
        type: "text",
        default: "",
        placeholder: "your-env-id",
        showIf: { key: "commentProvider", equals: "twikoo" },
        help: "腾讯云 / Vercel / 私有部署的环境 ID 或域名。",
      },
      {
        key: "disqusShortname",
        label: "Disqus 站点短名",
        type: "text",
        default: "",
        placeholder: "example",
        showIf: { key: "commentProvider", equals: "disqus" },
      },
      {
        key: "utterancesRepo",
        label: "Utterances 仓库",
        type: "text",
        default: "",
        placeholder: "owner/repo",
        showIf: { key: "commentProvider", equals: "utterances" },
      },
      {
        key: "utterancesTerm",
        label: "Issue 映射",
        type: "select",
        default: "pathname",
        half: true,
        showIf: { key: "commentProvider", equals: "utterances" },
        options: [
          { value: "pathname", label: "路径名（推荐）" },
          { value: "url", label: "URL" },
          { value: "title", label: "标题" },
          { value: "issue-number", label: "Issue 编号" },
          { value: "og-desc", label: "Og 描述" },
        ],
      },
      { key: "group_avatar", label: "头像", type: "group" },
      {
        key: "avatarSource",
        label: "头像源",
        type: "select",
        default: "gravatar",
        help: "仅对「系统自带」评论生效。QQ 邮箱会自动解析为 QQ 头像。",
        options: [
          { value: "gravatar", label: "Gravatar（国际）" },
          { value: "cn-gravatar", label: "Gravatar 国内镜像" },
          { value: "cravatar", label: "Cravatar（酷家）" },
          { value: "weavatar", label: "WeAvatar" },
          { value: "libravatar", label: "Libravatar" },
          { value: "qq", label: "QQ 邮箱 → QQ 头像" },
          { value: "none", label: "无头像" },
        ],
      },
      {
        key: "avatarSize",
        label: "头像尺寸",
        type: "number",
        default: 80,
        min: 16,
        max: 200,
        half: true,
      },
      {
        key: "avatarRating",
        label: "内容分级",
        type: "select",
        default: "g",
        half: true,
        options: [
          { value: "g", label: "G" },
          { value: "pg", label: "PG" },
          { value: "r", label: "R" },
          { value: "x", label: "X" },
        ],
      },
      {
        key: "avatarDefault",
        label: "缺省头像",
        type: "text",
        default: "identicon",
        placeholder: "identicon / mp / retro / robohash / monsterid / 404 / blank",
        help: "邮箱无头像时 Gravatar 系显示的占位图。",
      },
    ],
  },
  {
    key: "advanced",
    label: "代码注入",
    icon: "Code",
    description: "原样插入到每个页面。用于统计脚本、站长验证、全站样式覆盖。",
    fields: [
      { key: "analyticsId", label: "统计 ID", type: "text", default: "", placeholder: "G-XXXXXXX" },
      { key: "customHead", label: "<head> 注入", type: "code", default: "" },
      { key: "customFooter", label: "</body> 前注入", type: "code", default: "" },
      { key: "customCss", label: "全站自定义 CSS", type: "code", default: "" },
    ],
  },
];
